# Travis CI script

language: c

sudo: false

env:
- BUILD_TYPE=default
- BUILD_TYPE=check_zproject
- BUILD_TYPE=check_zproto
- BUILD_TYPE=valgrind

services: 
- docker

addons:
  apt:
    packages:
    - uuid-dev
    - valgrind
    - git

script: ./ci_build.sh
